# -*- python -*-

def pkg_deps(ctx):
    return

def configure(ctx):
    return

def build(ctx):
    ctx(
        features="cxx cxxshlib",
        name="rootcomps",
        source="src/rootcomps.cxx",
        target="rootcomps",
        use="ROOT",
        )
    return

def install(ctx):
    return
